### ISSUE TITLE
Not able to open .data and .o files

### ISSUE THREAD

**Issue by sumaiyadabeer** [acsl-technion/nuevomatch#4]
Please share the format of the data and its encoding. Files are opening in binaries that are not readable. Tried Gedit, Visual Studio, and head command with no luck

**Comment by alonrs** [comment]
Hi  @sumaiyadabeer,
The object files (.o) are regular ELF binary objects; you can read them using objdump.
```bash
objdump -d file.o | less
```
The data files (.data) have a custom binary format (see [here](https://github.com/acsl-technion/nuevomatch/blob/dca537b3db6c840d170e19a70cf9df8ef39f416e/src/nuevomatch.cpp#L67)), so the only way to read them is using hex-viewer applications such as xxd.
```bash
xxd file.data | less
```
